### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by hozuki** [lawrencegripper/FiddlerDnsForwarder#1]
Hello Lawrence,

I'm making something, a part of which would be an adaptation of this repo. Could you please provide a license so I can reference it in a right way?

Cheers.

**Comment by lawrencegripper** [comment]
All done - be interested to know what your building, if you don't mind sharing?

**Comment by hozuki** [comment]
Sure. It is a MITM proxy to monitor - and modify if needed - communications between app and server. The target app is set to ignore device proxy settings (and I can't change that), so vanilla Fiddler could not work. I have to build a DNS server, redirect the access to a local port, and handle interested network communications on a local PC, similar to your situation.
